language: go
sudo: required
go:
  - 1.8.3
install: true

before_script:
  - mkdir -p $HOME/gopath/src/github.com/go-chassis/mesher
  - rsync -az ${TRAVIS_BUILD_DIR}/ $HOME/gopath/src/github.com/go-chassis/mesher
  - export TRAVIS_BUILD_DIR=$HOME/gopath/src/github.com/go-chassis/mesher
  - cd $HOME/gopath/src/github.com/go-chassis/mesher
jobs:
  include:
    - stage: Format Checker
      script: bash -x scripts/travis/formatChecker.sh
    - stage: DeadCode Checker
      script:
        - go get -u github.com/tsenart/deadcode
        - bash -x scripts/travis/deadCodeChecker.sh
    - stage: Misspell Checker
      script:
        - go get -u github.com/client9/misspell
        - bash -x scripts/travis/misspellChecker.sh
    - stage: GoConst Checker
      script:
        - go get -u github.com/jgautheron/goconst/cmd/goconst
        - bash -x scripts/travis/goConstChecker.sh
